/**
 * Stream Deck plugin host — re-exports the shared runtime bootstrap.
 */
export {
  CHAT_LEVEL_BINDING_ID,
  GAME_LEVEL_BINDING_ID,
  GAME_LISTEN_BINDING_ID,
  getCapabilityCore,
  HEADPHONES_LEVEL_BINDING_ID,
  MIC_COMP_BINDING_ID,
  MIC_GAIN_BINDING_ID,
  MIC_HPF_BINDING_ID,
  MIC_MONITOR_BINDING_ID,
  MIC_MUTE_BINDING_ID,
  MUSIC_LEVEL_BINDING_ID,
  PAD_1_BINDING_ID,
  PAD_BANK_BINDING_ID,
  RECORD_BINDING_ID,
} from "@rode-control/host";
